- name: Log in (obtain access token) on Openshift
  redhat.openshift.openshift_auth:
    host: "{{ ocphost }}"
    username: "{{ ocpuser }}"
    password: "{{ ocppass }}"
    validate_certs: false
  register: openshift_auth_results

- name: Creating project on Openshift
  kubernetes.core.k8s:
    host: "{{ ocphost }}"
    api_key: "{{openshift_auth_results.openshift_auth.api_key}}"
    validate_certs: false
    api_version: v1
    template: namespace.yaml
    state: present
  register: namespace

- name: Log out from Openshift
  redhat.openshift.openshift_auth:
    host: "{{ ocphost }}"
    api_key: "{{openshift_auth_results.openshift_auth.api_key}}"
    validate_certs: false
    state: absent
  when: openshift_auth_results.openshift_auth.api_key is defined
  ignore_errors: true