- name: Logando no openshift via ansible
  community.okd.openshift_auth:
    host: https://api.url:6443
    username: "{{user}}"
    password: "{{pass}}"
    validate_certs: false
  register: openshift_auth_results

- name: Log in (obtain access token)
  redhat.openshift.openshift_auth:
    host: https://api.orizon.chiaret.to:6443
    username: chiaretto
    password: "VMware1!"
  register: openshift_auth_results

- name: Criando projeto no ambiente corporativo
  kubernetes.core.k8s:
    host: https://api.url:6443
    api_key: "{{openshift_auth_results.openshift_auth.api_key}}"
    validate_certs: false
    api_version: v1
    template: namespace.yaml
    state: present
  register: namespace

- name: Logando no openshift via shell
  ansible.builtin.shell: |
    oc login --token={{openshift_auth_results.openshift_auth.api_key}} --server=https://api.url:6443 || /bin/true

- name: Adicionando grupo admin ao projeto
  ansible.builtin.shell: | 
    oc adm policy add-role-to-group admin GRP-OCPDH-{{namespaceocp | upper}}-ADMIN \
    -n {{namespace.result.metadata.name}}
  
- name: Fazendo logout do openshift via ansible
  community.okd.openshift_auth:
    host: https://api.url:6443
    api_key: "{{openshift_auth_results.openshift_auth.api_key}}"
    validate_certs: false
    state: absent
  when: openshift_auth_results.openshift_auth.api_key is defined
  ignore_errors: true

- name: Fazendo logout do openshift via shell
  ansible.builtin.shell: oc logout || /bin/true