apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: "node-role.kubernetes.io/prd=true"
    openshift.io/requester: "{{tower_user_name}}"
    openshift.io/description: "{{descriptionocp | capitalize}} (owner-{{tower_user_name}})"
    openshift.io/display-name: "{{namespaceocp | capitalize}}"
  name: "{{namespaceocp | lower}}"