- name: Creating the team that will be sync with AD
  ansible.builtin.uri:
    url: "{{ quayhost }}/api/v1/organization/orizon_{{namespaceocp | lower}}/team/admins"
    method: PUT
    headers:
      Authorization: "Bearer {{ quay_token }}"
    body_format: json
    body: {"role": "admin", "description": "created by AAP"}

- name: Sync with Quay
  ansible.builtin.uri:
    url: "{{ quayhost }}/api/v1/organization/orizon_{{namespaceocp | lower}}/team/admins/syncing"
    method: POST
    headers:
      Authorization: "Bearer {{ quay_token }}"
    body_format: json
    body: {"group_dn": "{{ group }}"}